require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"

RSpec/ExampleLength:
  Max: 15

RSpec/FactoryBot/CreateList:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false
