#!/usr/bin/env ruby

require "asdf_discover"
require "fileutils"

FileUtils.cd(ARGV.first) if ARGV.first

if File.exist?(AsdfDiscover::TOOL_VERSIONS)
  puts "#{AsdfDiscover::TOOL_VERSIONS} already exists!"
  exit(1)
end

result = AsdfDiscover.search

unless result.any?
  puts "No tool versions found!"
  exit(1)
end

unless result.consistent?
  result.conflicts.each do |conflict|
    puts "Discovered multiple versions for #{conflict.tool}:"
    conflict.sources.each do |source|
      puts "  - #{source.version} from #{source.source}"
    end
    puts
  end
  puts "You should manually reconcile which version to use"
  puts ".tool-versions will include all versions discovered"
  puts "asdf, by default, will use the first entry"
end

File.open(AsdfDiscover::TOOL_VERSIONS, "w") do |f|
  result.tool_versions.each do |tool_version|
    f.puts "#{tool_version.tool} #{tool_version.version} # from #{tool_version.source}"
  end
end
